-- Create Comic Stories Table
CREATE TABLE IF NOT EXISTS public.comic_stories (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    topic text,
    level text,
    grammar_scope text,
    story text,
    sentences jsonb,
    illustrations text[],
    glosses jsonb
);
ALTER TABLE public.comic_stories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.comic_stories;
CREATE POLICY "Allow public read access" ON public.comic_stories FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access" ON public.comic_stories;
CREATE POLICY "Allow public write access" ON public.comic_stories FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update access" ON public.comic_stories;
CREATE POLICY "Allow public update access" ON public.comic_stories FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public delete access" ON public.comic_stories;
CREATE POLICY "Allow public delete access" ON public.comic_stories FOR DELETE USING (true);

-- Create Books Table
CREATE TABLE IF NOT EXISTS public.books (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  title TEXT,
  author TEXT,
  pages JSONB,
  "coverIllustrationUri" TEXT,
  topic TEXT,
  level TEXT,
  "grammarScope" TEXT
);
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.books;
CREATE POLICY "Allow public read access" ON public.books FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access" ON public.books;
CREATE POLICY "Allow public write access" ON public.books FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update access" ON public.books;
CREATE POLICY "Allow public update access" ON public.books FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public delete access" ON public.books;
CREATE POLICY "Allow public delete access" ON public.books FOR DELETE USING (true);

-- Create Expanded Words Table
CREATE TABLE IF NOT EXISTS public.expanded_words (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    word text NOT NULL,
    expansion text,
    language character varying,
    lemma text,
    tags text[]
);
ALTER TABLE public.expanded_words ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.expanded_words;
CREATE POLICY "Allow public read access" ON public.expanded_words FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access" ON public.expanded_words;
CREATE POLICY "Allow public write access" ON public.expanded_words FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update access" ON public.expanded_words;
CREATE POLICY "Allow public update access" ON public.expanded_words FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public delete access" ON public.expanded_words;
CREATE POLICY "Allow public delete access" ON public.expanded_words FOR DELETE USING (true);

-- Create Notes Table
CREATE TABLE IF NOT EXISTS public.notes (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    content text,
    tags text[],
    is_pinned boolean DEFAULT false,
    folder_path text
);
-- Add the editor_type column separately to avoid errors on existing tables
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS editor_type text DEFAULT 'default'::text;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.notes;
CREATE POLICY "Allow public read access" ON public.notes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access" ON public.notes;
CREATE POLICY "Allow public write access" ON public.notes FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update access" ON public.notes;
CREATE POLICY "Allow public update access" ON public.notes FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public delete access" ON public.notes;
CREATE POLICY "Allow public delete access" ON public.notes FOR DELETE USING (true);
